version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    networks:
      - my-network

  redis:
    image: redis:7.0.15
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network: