receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # OTLP gRPC 接口

exporters:
  prometheus:
    endpoint: "otel-collector:8889"
    namespace: "cfc_studio_frank"
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
