scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "onlinejudge"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ["onlinejudge:8085"]