// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package integration

import (
	"oj/internal/article/service"
)

// Injectors from wire.go:

func InitArticleService() *service.ArticleService {
	articleService := service.NewArticleService()
	return articleService
}
