// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package article

import (
	"oj/internal/article/service"
	"oj/internal/article/web"
)

// Injectors from wire.go:

func InitArticleHandler() *web.ArticleHandler {
	articleService := service.NewArticleService()
	articleHandler := web.NewArticleHandler(articleService)
	return articleHandler
}
