// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package judgement

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"oj/internal/judgement/repository"
	"oj/internal/judgement/repository/cache"
	"oj/internal/judgement/service/local"
	"oj/internal/judgement/service/remote"
	"oj/internal/judgement/web"
	"oj/internal/problem"
	"os"
)

// Injectors from wire.go:

func InitLocalJudgement(cmd redis.Cmdable, db *gorm.DB) *web.LocalSubmitHandler {
	localSubmitCache := cache.NewLocalSubmitCache(cmd)
	localSubmitRepo := repository.NewLocalSubmitRepo(localSubmitCache)
	problemRepository := problem.InitProblemRepo(cmd, db)
	locSubmitService := local.NewLocSubmitService(localSubmitRepo, problemRepository)
	localSubmitHandler := web.NewLocalSubmitHandler(locSubmitService)
	return localSubmitHandler
}

func InitRemoteJudgement(cmd redis.Cmdable, db *gorm.DB) *web.SubmissionHandler {
	submitCache := cache.NewSubmitCache(cmd)
	submitRepository := repository.NewSubmitRepository(submitCache)
	problemRepository := problem.InitProblemRepo(cmd, db)
	string2 := InitJudgeKey(cmd, db)
	submitService := remote.NewSubmitService(submitRepository, problemRepository, string2)
	submissionHandler := web.NewSubmissionHandler(submitService)
	return submissionHandler
}

// wire.go:

var LocalSet = wire.NewSet(cache.NewLocalSubmitCache, repository.NewLocalSubmitRepo, problem.InitProblemRepo, local.NewLocSubmitService, web.NewLocalSubmitHandler)

var RemoteSet = wire.NewSet(cache.NewSubmitCache, repository.NewSubmitRepository, problem.InitProblemRepo, remote.NewSubmitService, web.NewSubmissionHandler)

func InitJudgeKey(cmd redis.Cmdable, db *gorm.DB) string {
	key, ok := os.LookupEnv("RAPIDAPI_KEY")
	if !ok {
		panic("environment variable rapidapiKey not found")
	}

	return key
}
