// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"oj/internal/problem/web"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	cmdable := InitRedis()
	v := GinMiddlewares(cmdable)
	db := InitDB()
	userHandler := InitUserHandler(db, cmdable)
	problemHandler := web.NewProblemHandler()
	engine := InitWebServer(v, userHandler, problemHandler)
	return engine
}

// wire.go:

var BaseSet = wire.NewSet(InitDB, InitRedis)
