// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package problem

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"oj/internal/problem/repository"
	"oj/internal/problem/repository/cache"
	"oj/internal/problem/repository/dao"
	"oj/internal/problem/service"
	"oj/internal/problem/web"
)

// Injectors from wire.go:

func InitProblemRepo(cmd redis.Cmdable, db *gorm.DB) repository.ProblemRepository {
	problemDao := dao.NewProblemDao(db)
	problemCache := cache.NewProblemCache(cmd)
	problemRepository := repository.NewProblemRepository(problemDao, problemCache)
	return problemRepository
}

func InitProblemHandler(cmd redis.Cmdable, db *gorm.DB) *web.ProblemHandler {
	problemRepository := InitProblemRepo(cmd, db)
	problemService := service.NewProblemService(problemRepository)
	problemHandler := web.NewProblemHandler(problemService)
	return problemHandler
}
