// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package problem

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"github.com/crazyfrankie/onlinejudge/internal/problem/repository"
	"github.com/crazyfrankie/onlinejudge/internal/problem/repository/cache"
	"github.com/crazyfrankie/onlinejudge/internal/problem/repository/dao"
	"github.com/crazyfrankie/onlinejudge/internal/problem/service"
	"github.com/crazyfrankie/onlinejudge/internal/problem/web"
)

// Injectors from wire.go:

func InitModule(cmd redis.Cmdable, db *gorm.DB) *Module {
	problemDao := dao.NewProblemDao(db)
	problemCache := cache.NewProblemCache(cmd)
	problemRepository := repository.NewProblemRepository(problemDao, problemCache)
	problemService := service.NewProblemService(problemRepository)
	problemHandler := web.NewProblemHandler(problemService)
	module := &Module{
		Hdl:  problemHandler,
		Repo: problemRepository,
	}
	return module
}
