// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"github.com/crazyfrankie/onlinejudge/internal/middleware/jwt"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitModule(cmd redis.Cmdable) *Module {
	handler := jwt.NewRedisJWTHandler(cmd)
	module := &Module{
		Hdl: handler,
	}
	return module
}
