// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/crazyfrankie/onlinejudge/internal/auth/jwt"
	ratelimit2 "github.com/crazyfrankie/onlinejudge/internal/auth/ratelimit"
	"github.com/crazyfrankie/onlinejudge/pkg/ratelimit"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitModule(limiter ratelimit.Limiter, cmd redis.Cmdable) *Module {
	handler := jwt.NewRedisJWTHandler(cmd)
	builder := ratelimit2.NewBuilder(limiter)
	loginJWTMiddlewareBuilder := NewLoginJWTMiddlewareBuilder(handler)
	module := &Module{
		Hdl:        handler,
		Builder:    builder,
		JWTBuilder: loginJWTMiddlewareBuilder,
	}
	return module
}
