// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitModule(cmd redis.Cmdable) *Module {
	jwtHandler := NewRedisJWTHandler(cmd)
	module := &Module{
		Hdl: jwtHandler,
	}
	return module
}

// wire.go:

type Module struct {
	Hdl JWTHandler
}
