// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"oj/internal/user/repository"
	"oj/internal/user/repository/cache"
	"oj/internal/user/repository/dao"
	"oj/internal/user/service"
	"oj/internal/user/web"
)

// Injectors from wire.go:

func InitHandler(db *gorm.DB, cmd redis.Cmdable) *web.UserHandler {
	codeCache := cache.NewRedisCodeCache(cmd)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmd)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	userHandler := initHandler(codeService, userService)
	return userHandler
}
